apiVersion: v2
version: 0.7.0
description: An extension of the official kafka-operator helm chart
name: cray-kafka-operator
keywords:
  - kafka-operator
home: https://github.com/Cray-HPE/cray-kafka-operator
sources:
  - https://github.com/strimzi/strimzi-kafka-operator
maintainers:
  - name: bo-quan
dependencies:
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: 0.15.0
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
appVersion: 0.15.0
annotations:
  artifacthub.io/license: MIT
