apiVersion: v2
version: 1.1.0
description: An extension of the official kafka-operator helm chart
name: cray-kafka-operator
keywords:
  - kafka-operator
home: https://github.com/Cray-HPE/cray-kafka-operator
sources:
  - https://github.com/strimzi/strimzi-kafka-operator
maintainers:
  - name: bo-quan
  - name: kburns-hpe
dependencies:
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: 0.27.1
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
appVersion: 0.27.1
annotations:
  artifacthub.io/images: |-
    - name: operator
      image: artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/operator:0.27.1
    - name: kafka-bridge
      image: artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/kafka-bridge:0.21.2
    - name: kafka-2.8.0
      image: artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/kafka:0.27.1-noJSM-chainsaw-kafka-2.8.0
    - name: kafka-2.8.1
      image: artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/kafka:0.27.1-noJSM-chainsaw-kafka-2.8.1
    - name: kafka-3.0.0
      image: artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/kafka:0.27.1-noJSM-chainsaw-kafka-3.0.0
  artifacthub.io/license: MIT
