# Default values for cray-kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
strimzi-kafka-operator:
  watchNamespaces:
    - services
    - sma

  image:
    repository: artifactory.algol60.net/artifactory/csm-docker/stable/quay.io/strimzi
    name: operator
    tag: 0.15.0
    imagePullPolicy: IfNotPresent
# Increase resources.limits.cpu to 8 to reduce cpu throttling
  resources:
    limits:
      cpu: "8"
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
