# Default values for cray-kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

strimzi-kafka-operator:
  watchNamespaces:
    - services
    - sma

  topicOperator:
    image:
      tagPrefix: 0.15.0-noJndiLookupClass
  userOperator:
    image:
      tagPrefix: 0.15.0-noJndiLookupClass
  kafkaInit:
    image:
      tagPrefix: 0.15.0-noJndiLookupClass

# Increase resources.limits.cpu to 8 to reduce cpu throttling
  resources:
    limits:
      cpu: "8"
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
          zookeeper:
      tagPrefix: 0.15.0-noJndiLookupClass


