# Default values for cray-kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
strimzi-kafka-operator:
  watchNamespaces:
    - services
    - sma

  image:
    registry: artifactory.algol60.net
    repository: csm-docker/stable/quay.io/strimzi
    name: operator
    tag: 0.27.1
    imagePullPolicy: IfNotPresent

  zookeeper:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  kafka:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  kafkaConnect:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  kafkaConnects2i:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  topicOperator:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: operator
      tag: 0.27.1
  userOperator:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: operator
      tag: 0.27.1
  kafkaInit:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: operator
      tag: 0.27.1
  tlsSidecarZookeeper:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  tlsSidecarKafka:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  tlsSidecarEntityOperator:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  kafkaMirrorMaker:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw
  kafkaBridge:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka-bridge
      tag: 0.21.2
  kafkaExporter:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/strimzi
      name: kafka
      tagPrefix: 0.27.1-noJSM-chainsaw

  # Increase resources.limits.cpu to 8 to reduce cpu throttling
  resources:
    limits:
      cpu: "8"
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
